# SCAN MAPPINGS
DISPLAY_PATH_TO_RESOURCE = "RESOURCE:{account_id}:{display_path}"
RULE_TO_COMPLIANCE = "RULE_TO_COMPLIANCE:{master_rule_id}"
CONTROL_TO_RULE = "CONTROL_TO_RULE:{control_id}"
RULE_METADATA = "RULE_METADATA:{master_rule_id}"
ACCOUNT_DETAILS = "ACCOUNT_METADATA:{account_id}"
CONTROL_METADATA = "CONTROL_METADATA:{control}"
SERVICE_AND_CATEGORY_FOR = "SERVICE_AND_CATEGORY_FOR:{resource_type}"
INTERNET_EXPOSED_RULES_FOR = "INTERNET_EXPOSED_RULES_FOR:{resource_type}"

# CACHED SCAN REPORTS
RESOURCE_REPORT = "SCAN:RESOURCE_REPORT:{account_id}"
RULES_REPORT = "SCAN:RULES_REPORT:{account_id}"
CONTROL_REPORT = "SCAN:CONTROL_REPORT:{account_id}"

FULL_RAW_REPORT = "SCAN:FULL_RAW_REPORT:{account_id}"

# RESOURCE CACHE
RES_DETAILS = "RES_DETAILS:{account_id}:{display_path}"

# ACCOUNT DETAILS
ACCOUNT_TO_SCHEMA = "ACCOUNT_TO_SCHEMA:{account_id}"
SCHEMA_TO_ACCOUNTS = "SCHEMA_TO_ACCOUNTS:{schema_name}"


# Anomaly/Threat rule processing results
ANOMALY_THREAT_RULE = "SCAN_REPORT:ANOMALY_THREAT_RULE_JSON:{account_id}"
LAST_ANOMALY_THREAT_RULE_PROC = "SCAN_REPORT:LAST_ANOMALY_THREAT_RULE_PROC:{account_id}"
ANOMALY_THREAT_RULE_FILE_CACHE = (
    "ANOMALY_THREAT_RULE_FILE_CACHE:{rule_file_name_without_suffix}"
)
