"""Compliance Constants."""

from __future__ import annotations

from scan_compute.utils.enum import CloudProvider

COMPLIANCES: dict[
    CloudProvider,
    dict[str, list[str | dict[str, str]]],
] = {
    CloudProvider.AWS: {
        "compliances_list": [
            "awaf",
            "cis",
            "cis_eks",
            "nist_rev4",
            "nist_rev5",
            "iso",
            "ccmv3",
            "ccm_v4.0.5",
            "pci_dss_v3.2.1",
            "gdpr",
            "soc2",
            "popi_act",
            "hipaa",
            "iso_2022",
            "fedramp",
            "cmmc",
            "fisma",
            "nydfs",
            "aws_fsbp",
            "sama_csf",
            "pci_dss_v4.0",
            "cbb",
        ],
        "compliances": [
            {
                "compliance_version": "awaf",
                "compliance_version_case": "AWS-Well-Architected_v2020-07-02",
                "compliance_control": "awaf",
                "compliance_rule": "AWAF",
                "is_selected": "true",
            },
            {
                "compliance_version": "aws-cis-1.3.0",
                "compliance_version_case": "CIS-AWS_v1.3.0",
                "compliance_control": "cis",
                "compliance_rule": "CIS",
                "is_selected": "true",
            },
            {
                "compliance_version": "aws-cis-eks-1.1.0",
                "compliance_version_case": "AWS-CIS-EKS-1.1.0",
                "compliance_control": "cis_eks",
                "compliance_rule": "CIS_EKS",
                "is_selected": "true",
            },
            {
                "compliance_version": "nist-800-53-rev-4",
                "compliance_version_case": "NIST-800-53_vRev4",
                "compliance_control": "nist_rev4",
                "compliance_rule": "NIST_Rev4",
                "is_selected": "true",
            },
            {
                "compliance_version": "nist-800-53-rev-5",
                "compliance_version_case": "NIST-800-53_vRev5",
                "compliance_control": "nist_rev5",
                "compliance_rule": "NIST_Rev5",
                "is_selected": "true",
            },
            {
                "compliance_version": "iso-27001-2013",
                "compliance_version_case": "ISO-27001_v2013",
                "compliance_control": "iso",
                "compliance_rule": "ISO",
                "is_selected": "true",
            },
            {
                "compliance_version": "iso-27001-2022",
                "compliance_version_case": "ISO-27001_v2022",
                "compliance_control": "iso_2022",
                "compliance_rule": "ISO_2022",
                "is_selected": "true",
            },
            {
                "compliance_version": "csa-ccm-3.0",
                "compliance_version_case": "CSA-CCM_v3.0.1",
                "compliance_control": "ccmv3",
                "compliance_rule": "CCM_V3",
                "is_selected": "true",
            },
            {
                "compliance_version": "ccm_v4.0.5",
                "compliance_version_case": "CSA-CCM_v4.0.5",
                "compliance_control": "ccm_v4.0.5",
                "compliance_rule": "CCM_v4.0.5",
                "is_selected": "true",
            },
            {
                "compliance_version": "pci_dss_v3.2.1",
                "compliance_version_case": "PCI-DSS_v3.2.1",
                "compliance_control": "pci_dss_v3.2.1",
                "compliance_rule": "PCI_DSS_v3.2.1",
                "is_selected": "true",
            },
            {
                "compliance_version": "gdpr",
                "compliance_version_case": "GDPR_v2016",
                "compliance_control": "gdpr",
                "compliance_rule": "GDPR",
                "is_selected": "true",
            },
            {
                "compliance_version": "soc2",
                "compliance_version_case": "SOC-2_v2017",
                "compliance_control": "soc2",
                "compliance_rule": "SOC2",
                "is_selected": "true",
            },
            {
                "compliance_version": "popi_act",
                "compliance_version_case": "POPI_Act_v2000",
                "compliance_control": "popi_act",
                "compliance_rule": "POPI_Act",
                "is_selected": "true",
            },
            {
                "compliance_version": "hipaa",
                "compliance_version_case": "HIPAA_v2013",
                "compliance_control": "hipaa",
                "compliance_rule": "HIPAA",
                "is_selected": "true",
            },
            {
                "compliance_version": "fedramp",
                "compliance_version_case": "FedRAMP",
                "compliance_control": "fedramp",
                "compliance_rule": "FedRAMP",
            },
            {
                "compliance_version": "cmmc",
                "compliance_version_case": "CMMC",
                "compliance_control": "cmmc",
                "compliance_rule": "CMMC",
            },
            {
                "compliance_version": "fisma",
                "compliance_version_case": "FISMA",
                "compliance_control": "fisma",
                "compliance_rule": "FISMA",
            },
            {
                "compliance_version": "nydfs",
                "compliance_version_case": "NYDFS",
                "compliance_control": "nydfs",
                "compliance_rule": "NYDFS",
            },
            {
                "compliance_version": "aws_fsbp",
                "compliance_version_case": "AWS_FSBP",
                "compliance_control": "aws_fsbp",
                "compliance_rule": "AWS_FSBP",
                "is_selected": "true",
            },
            {
                "compliance_version": "sama_csf",
                "compliance_version_case": "SAMA_CSF",
                "compliance_control": "sama_csf",
                "compliance_rule": "SAMA_CSF",
                "is_selected": "true",
            },
            {
                "compliance_version": "pci_dss_v4.0",
                "compliance_version_case": "PCI-DSS_v4.0",
                "compliance_control": "pci_dss_v4.0",
                "compliance_rule": "PCI_DSS_v4.0",
                "is_selected": "true",
            },
            {
                "compliance_version": "cbb",
                "compliance_version_case": "CBB",
                "compliance_control": "cbb",
                "compliance_rule": "CBB",
                "is_selected": "true",
            },
        ],
    },
    CloudProvider.GCP: {
        "compliances_list": [
            "gcaf",
            "cis",
            "nist_rev4",
            "nist_rev5",
            "iso",
            "ccmv3",
            "ccm_v4.0.5",
            "pci_dss_v3.2.1",
            "gdpr",
            "soc2",
            "popi_act",
            "hipaa",
            "iso_2022",
        ],
        "compliances": [
            {
                "compliance_version": "gcaf",
                "compliance_version_case": "Google Cloud Architecture Framework",
                "compliance_control": "gcaf",
                "compliance_rule": "GCAF",
                "is_selected": "true",
            },
            {
                "compliance_version": "gcp-cis-2.0.0",
                "compliance_version_case": "CIS-GCP_v2.0.0",
                "compliance_control": "cis",
                "compliance_rule": "CIS",
                "is_selected": "true",
            },
            {
                "compliance_version": "nist-800-53-rev-4",
                "compliance_version_case": "NIST-800-53_vRev4",
                "compliance_control": "nist_rev4",
                "compliance_rule": "NIST_Rev4",
                "is_selected": "true",
            },
            {
                "compliance_version": "nist-800-53-rev-5",
                "compliance_version_case": "NIST-800-53_vRev5",
                "compliance_control": "nist_rev5",
                "compliance_rule": "NIST_Rev5",
                "is_selected": "true",
            },
            {
                "compliance_version": "iso-27001-2013",
                "compliance_version_case": "ISO-27001_v2013",
                "compliance_control": "iso",
                "compliance_rule": "ISO",
                "is_selected": "true",
            },
            {
                "compliance_version": "iso-27001-2022",
                "compliance_version_case": "ISO-27001_v2022",
                "compliance_control": "iso_2022",
                "compliance_rule": "ISO_2022",
                "is_selected": "true",
            },
            {
                "compliance_version": "csa-ccm-3.0",
                "compliance_version_case": "CSA-CCM_v3.0.1",
                "compliance_control": "ccmv3",
                "compliance_rule": "CCM_V3",
                "is_selected": "true",
            },
            {
                "compliance_version": "ccm_v4.0.5",
                "compliance_version_case": "CSA-CCM_v4.0.5",
                "compliance_control": "ccm_v4.0.5",
                "compliance_rule": "CCM_v4.0.5",
                "is_selected": "true",
            },
            {
                "compliance_version": "pci_dss_v3.2.1",
                "compliance_version_case": "PCI-DSS_v3.2.1",
                "compliance_control": "pci_dss_v3.2.1",
                "compliance_rule": "PCI_DSS_v3.2.1",
                "is_selected": "true",
            },
            {
                "compliance_version": "gdpr",
                "compliance_version_case": "GDPR_v2016",
                "compliance_control": "gdpr",
                "compliance_rule": "GDPR",
                "is_selected": "true",
            },
            {
                "compliance_version": "soc2",
                "compliance_version_case": "SOC-2_v2017",
                "compliance_control": "soc2",
                "compliance_rule": "SOC2",
                "is_selected": "true",
            },
            {
                "compliance_version": "popi_act",
                "compliance_version_case": "POPI_Act_v2000",
                "compliance_control": "popi_act",
                "compliance_rule": "POPI_Act",
                "is_selected": "true",
            },
            {
                "compliance_version": "hipaa",
                "compliance_version_case": "HIPAA_v2013",
                "compliance_control": "hipaa",
                "compliance_rule": "HIPAA",
                "is_selected": "true",
            },
        ],
    },
}
