"""Table Constants."""

CLIENT_SUPPRESSION = 'public."tClient_Suppressed_Events"'
SCAN_REPORT = '{schema_name}."tClient_Scan_Report"'
ACCOUNT = '{schema_name}."tClient_MasterAccount"'

RESOURCE_TABLE = '{schema_name}."tClient_Resource_Details"'
CONTROL_TABLE = '{schema_name}."tClient_Control_Details"'
EVENTS_TABLE = '{schema_name}."tCSPM_Events"'
RTM_QUEUE = '{schema_name}."tCSPM_Real_Time_Queue"'
RULE_EXPANSION = '{schema_name}."tClient_Rule_Expansion"'
RULES_DATABASE = '{schema_name}."tRules_Database"'
LAMBDA_SECRET = '{schema_name}."tLambdaSecret"'
RULES_DB = '{schema_name}."tRules_DB"'
POLICIES = '{schema_name}."policies"'
VULNERABILITY = '{schema_name}."tVulnerabilityData"'
VULNERABILITYGROUPEDDATA = '{schema_name}."tVulnerabilityGroupedData"'
RULE_EXCEPTION = '{schema_name}."tRules_Exceptions_DB"'
SECURITY_SCORE = '{schema_name}."tSecurityScoreData"'
ALERT_SEVERIITY = '{schema_name}."tAlertsSeverity"'
NOTIFICATION_LOGS = '{schema_name}."tNotification_Logs"'
TNOTIFICATION = '{schema_name}."tNotification"'
TEXCEPTION_RISK_REPORT = '{schema_name}."tException_Risk_Report"'
SERVICE_CATEGORY_MAPPING = 'public."Service_Category_Mapping"'
MITRE_MAPPING = 'public."mitre_rule_mapping"'
GEO_CLOUD_MAPPING = 'public."tGeo_Cloud_Mapping"'
RTM_LOGS = '{schema_name}."tCSPM_Real_Time_Logs"'
CSPM_SCHEDULER = '{schema_name}."tCSPM_Scheduler"'
ORG_SCHEMAS = 'public."tOrgSchemas"'
ORG_SUBTENANTS = 'public."tOrgSubTenants"'
SCANNER_INSTANCES = 'public."tClientScannerInstances"'
USER_TENANTS = 'public."tUserTenants"'
USER_GROUPS = 'public."tUserGroups"'
RTM_SCAN = 'public."tCSPMRealTimeScan"'
COMPLIANCE_CONTROL = 'public."tComplianceControl"'
RULE_REM_POLICY = 'public."tRuleRemediationPolicy"'
ANAMOLOUS_THREAT_MAPPING = 'public."AnamolousThreatMapping"'
AUTO_SCAN_REPORT = '{schema_name}."tClient_Scan_Report_Autonomous"'
USER_POLICY = '{schema_name}."tUserPolicy"'
RES_EXCEPTION = '{schema_name}."tResource_Exception_DB"'
REM_TABLE = '{schema_name}."remediations"'
POLICIES_TABLE = '{schema_name}."policies"'
OBJECTS_DETAILS = '{schema_name}."tClient_Objects_Detail"'
MALWARE_SCAN_DETAIL = '{schema_name}."tMalware_Scan_Detail"'
SCAN_DURATION = '{schema_name}."tClient_Scan_Duration"'

GCP_MARKETPLACE_RES_DETAILS = 'public."gcp_marketplace_billing"'

DATA_SECURITY_FINDINGS = '{schema_name}."Data_Security_Findings"'
NOTIFICATION_JSON_DATA = 'public."tNotificationJsonData"'
